title: Same but different
hero_image: images/banner.png
description: Create a fun game to try and improve a user’s concentration and help them focus and relax.
version: 1
listed: false
copyedit: false
last_tested: "2020-06-30"
steps:
  - title: Introduction
  - title: Choose your theme
  - title: Get a sprite moving
  - title: Add more sprites
  - title: More ideas
  - title: Share your project
  - title: Reflect on your project
  - title: What next?
