title: Same but different
hero_image: images/banner.png
description: Create a fun game to try and improve a player’s concentration and help them focus and relax
version: 1
listed: false
copyedit: false
last_tested: "2020-06-30"
steps:
  - title: Introduction
  - title: Develop your theme
  - title: Develop sprite costumes
  - title: When I receive move
  - title: Variables
  - title: More sprites
  - title: Share your project
  - title: Reflect on your project
  - title: What next?
